In [2]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv("../00_data/04_output/SAMIs_pop.csv")
df.loc[df['factor'] == 'gdp', 'factor'] = 'GDP'
df.loc[df['factor'] == 'mental_health_providers', 'factor'] = 'MHP'
df.loc[df['factor'] == 'DEPRESSION', 'factor'] = 'DEP'
df.loc[df['factor'] == 'children_single_parent', 'factor'] = 'SP'
df.loc[df['factor'] == 'BINGE', 'factor'] = 'ED'
df.loc[df['factor'] == 'pedestrian_3leg_intersections_total', 'factor'] = 'INT'
df.loc[df['factor'] == 'life_total', 'factor'] = 'LE'
df.loc[df['factor'] == 'DISABILITY', 'factor'] = 'DIS'
df.loc[df['factor'] == 'noise90n', 'factor'] = 'NOI'

df_fsami = pd.read_csv('../00_data/04_output/FsAMIs_pop_bestk.csv')

In [29]:
df_fsami

,Unnamed: 0,cbsacode,factor,k,baseline_moran_value,baseline_moran_p,final_moran_value,final_moran_p,selected_m_eigs,FsAMI,beta,p_value,CI_lower,CI_upper,AIC,BIC,AICc,CV_RMSE_final,LASSO_R2_unused,LASSO_n_eigs_unused
0,0,10100.0,ED,11,0.653093,0.001,0.026501,0.063,44,0.004854,1.022914,0.0,1.018191,1.027637,-1842.055484,-1622.441186,-1836.833262,0.084525,0.000000,0
1,1,10140.0,ED,11,0.653093,0.001,0.026501,0.063,44,0.059234,1.022914,0.0,1.018191,1.027637,-1842.055484,-1622.441186,-1836.833262,0.084525,0.000000,0
2,2,10180.0,ED,11,0.653093,0.001,0.026501,0.063,44,0.012878,1.022914,0.0,1.018191,1.027637,-1842.055484,-1622.441186,-1836.833262,0.084525,0.000000,0
3,3,10220.0,ED,11,0.653093,0.001,0.026501,0.063,44,-0.075007,1.022914,0.0,1.018191,1.027637,-1842.055484,-1622.441186,-1836.833262,0.084525,0.000000,0
4,4,10300.0,ED,11,0.653093,0.001,0.026501,0.063,44,-0.028065,1.022914,0.0,1.018191,1.027637,-1842.055484,-1622.441186,-1836.833262,0.084525,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40391,40391,49660.0,LE,6,0.597991,0.001,0.033470,0.077,56,-0.029065,1.005733,0.0,1.004542,1.006924,-4220.261580,-3943.356594,-4211.874325,0.022181,0.128918,60
40392,40392,49700.0,LE,6,0.597991,0.001,0.033470,0.077,56,-0.000811,1.005733,0.0,1.004542,1.006924,-4220.261580,-3943.356594,-4211.874325,0.022181,0.128918,60
40393,40393,49740.0,LE,6,0.597991,0.001,0.033470,0.077,56,0.028536,1.005733,0.0,1.004542,1.006924,-4220.261580,-3943.356594,-4211.874325,0.022181,0.128918,60
40394,40394,49780.0,LE,6,0.597991,0.001,0.033470,0.077,56,-0.011425,1.005733,0.0,1.004542,1.006924,-4220.261580,-3943.356594,-4211.874325,0.022181,0.128918,60
40395,40395,49820.0,LE,6,0.597991,0.001,0.033470,0.077,56,0.024411,1.005733,0.0,1.004542,1.006924,-4220.261580,-3943.356594,-4211.874325,0.022181,0.128918,60

In [33]:
factors = ["DEP", "ED", "DIS", "SP", "MHP", "GDP", "INT"]

df_sami_fuc = (
    df[['factor','beta','p_value','CI_lower','CI_upper']]
    .drop_duplicates()
    .loc[lambda x: x['factor'].isin(factors)]
    .reset_index(drop=True)
)
df_fsami_fuc = (
    df_fsami[['factor','beta','p_value','CI_lower','CI_upper']]
    .drop_duplicates()
    .loc[lambda x: x['factor'].isin(factors)]
    .reset_index(drop=True)
)

In [32]:
df_sami_fuc

  factor      beta        p_value  CI_lower  CI_upper
0     ED  1.011609   0.000000e+00  1.004052  1.019167
1    DEP  0.991533   0.000000e+00  0.984926  0.998141
2    DIS  0.962573   0.000000e+00  0.955277  0.969870
3     SP  1.016121   0.000000e+00  0.997979  1.034263
4    MHP  1.156165  8.370687e-318  1.119080  1.193251
5    GDP  1.052587   0.000000e+00  1.033595  1.071580
6    INT  0.889369  2.371515e-322  0.862108  0.916630

In [34]:
df_fsami_fuc

  factor      beta  p_value  CI_lower  CI_upper
0     ED  1.022914      0.0  1.018191  1.027637
1    DEP  0.993780      0.0  0.989925  0.997635
2     SP  1.028498      0.0  1.014216  1.042780
3    MHP  1.151497      0.0  1.123054  1.179941
4    GDP  1.081289      0.0  1.065516  1.097063
5    DIS  0.959116      0.0  0.954115  0.964116
6    INT  0.895658      0.0  0.874712  0.916603